// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./supabase";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const frequencyTypeSchema = z.union([
  z.literal("daily"),
  z.literal("monthly"),
  z.literal("interval"),
]);

export const habitsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  days: z.array(z.number()).optional().nullable(),
  end_date: z.string().optional().nullable(),
  frequencytype: frequencyTypeSchema.optional().nullable(),
  icon: z.string().optional().nullable(),
  id: z.string(),
  interval: z.number().optional().nullable(),
  name: z.string().optional().nullable(),
  projectid: z.string().optional().nullable(),
  reminders: z.array(z.number()).optional().nullable(),
  start_date: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  userid: z.string().optional().nullable(),
  week_days: z.array(z.number()).optional().nullable(),
});

export const habitsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  days: z.array(z.number()).optional().nullable(),
  end_date: z.string().optional().nullable(),
  frequencytype: frequencyTypeSchema.optional().nullable(),
  icon: z.string().optional().nullable(),
  id: z.string().optional(),
  interval: z.number().optional().nullable(),
  name: z.string().optional().nullable(),
  projectid: z.string().optional().nullable(),
  reminders: z.array(z.number()).optional().nullable(),
  start_date: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  userid: z.string().optional().nullable(),
  week_days: z.array(z.number()).optional().nullable(),
});

export const profilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  updated_at: z.string().nullable(),
  username: z.string().nullable(),
  website: z.string().nullable(),
});

export const profilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const profilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const colorTypeSchema = z.union([
  z.literal("red"),
  z.literal("blue"),
  z.literal("green"),
  z.literal("yellow"),
  z.literal("purple"),
  z.literal("pink"),
  z.literal("indigo"),
  z.literal("teal"),
  z.literal("cyan"),
  z.literal("orange"),
]);

export const projectsInsertSchema = z.object({
  color: colorTypeSchema,
  id: z.string(),
  name: z.string(),
  userid: z.string().optional().nullable(),
});

export const projectsUpdateSchema = z.object({
  color: colorTypeSchema.optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  userid: z.string().optional().nullable(),
});

export const habitsRowSchema = z.object({
  created_at: z.string().nullable(),
  days: z.array(z.number()).nullable(),
  end_date: z.string().nullable(),
  frequencytype: frequencyTypeSchema.nullable(),
  icon: z.string().nullable(),
  id: z.string(),
  interval: z.number().nullable(),
  name: z.string().nullable(),
  projectid: z.string().nullable(),
  reminders: z.array(z.number()).nullable(),
  start_date: z.string().nullable(),
  updated_at: z.string().nullable(),
  userid: z.string().nullable(),
  week_days: z.array(z.number()).nullable(),
});

export const projectsRowSchema = z.object({
  color: colorTypeSchema,
  id: z.string(),
  name: z.string(),
  userid: z.string().nullable(),
});
